export default [
  {
    category: "App Design",
    imgSrc: "/images/portfolio/01.jpg",
    title: "Management Software Mobile Application",
    description: "Custom mobile applications designed to enhance productivity and efficiency.",
    details: "Our apps are tailored to meet your unique business needs, offering a seamless user experience.",
  },
  {
    category: "Branding",
    imgSrc: "/images/portfolio/02.jpg",
    title: "ID Card Solutions",
    description: "Secure and reliable ID card services from design to implementation.",
    details: "We provide comprehensive solutions for employee identification and workplace security.",
  },
  {
    category: "Web Design",
    imgSrc: "/images/portfolio/03.jpg",
    title: "Professional Website Design",
    description: "Visually appealing and user-friendly websites that capture your brand's essence.",
    details: "Our designs are SEO-optimized to help you stand out and engage your audience effectively.",
  },
  {
    category: "Networking",
    imgSrc: "/images/portfolio/04.jpg",
    title: "Networking Solutions (LAN, WAN)",
    description: "Robust networking solutions to ensure seamless connectivity.",
    details: "Whether you need a local area network (LAN) or wide area network (WAN), we provide expert support and maintenance.",
  },
  {
    category: "E-Learning",
    imgSrc: "/images/portfolio/05.jpg",
    title: "E-Learning Digital Platform",
    description: "Innovative platforms for engaging and interactive learning experiences.",
    details: "Our solutions cater to educational institutions and corporate training needs, making learning more dynamic.",
  },
  {
    category: "Security",
    imgSrc: "/images/portfolio/06.jpg",
    title: "CCTV Security System",
    description: "State-of-the-art CCTV systems for comprehensive surveillance.",
    details: "Protect your assets with our advanced security solutions, including remote monitoring capabilities.",
  },
  {
    category: "Marketing",
    imgSrc: "/images/portfolio/01.jpg",
    title: "Digital Marketing",
    description: "Boost your online presence with our targeted digital marketing strategies.",
    details: "From SEO to social media marketing, we help you reach your target audience effectively.",
  },
  {
    category: "Education",
    imgSrc: "/images/portfolio/03.jpg",
    title: "Smart Class Solutions",
    description: "Revolutionize education with our technology-enhanced learning environments.",
    details: "Our smart class solutions make learning more interactive and engaging for students.",
  },
  {
    category: "Communication",
    imgSrc: "/images/portfolio/10.png",
    title: "Video Conferencing Solution",
    description: "High-quality video conferencing systems for effective communication.",
    details: "Our solutions offer crystal-clear audio and video, ensuring seamless collaboration.",
  },
  {
    category: "Security",
    imgSrc: "/images/portfolio/9.jpg",
    title: "Biometric Solutions",
    description: "Advanced biometric technology for secure access control.",
    details: "From fingerprint scanners to facial recognition systems, we enhance your security infrastructure.",
  },
  {
    category: "IT Services",
    imgSrc: "/images/portfolio/9.jpg",
    title: "Computer AMC",
    description: "Comprehensive annual maintenance contracts for IT infrastructure.",
    details: "We provide regular maintenance and prompt support to keep your systems running smoothly.",
  },
  {
    category: "Education",
    imgSrc: "/images/portfolio/11.jpg",
    title: "Interactive LED Touch Panels",
    description: "Engaging displays perfect for presentations and collaborative work.",
    details: "Our LED touch panels offer a dynamic and intuitive user experience, enhancing productivity.",
  }
];
